image:
  repository: yasirabid96/dask-worker-rclone
  tag: latest
  pullPolicy: Always

scheduler:
  serviceType: NodePort

worker:
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 50
    cpu:
      targetAverageUtilization: 70

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

nfs:
  server: 10.255.135.231
  path: /srv/nfs
  mountPath: /mnt/nfs # This should match what's used in volumeMounts
  size: 500Gi
  request: 1Gi
