image:
  repository: yasirabid96/dask-worker-rclone
  tag: latest
  pullPolicy: Always

scheduler:
  serviceType: NodePort

worker:
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 50
    cpu:
      targetAverageUtilization: 70

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  volumeMounts:
    - name: dask-nfs-volume
      mountPath: /mnt/nfs

  volumes:
    - name: dask-nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc # 👈 manually created PVC bound to static PV

nfs:
  server: 10.0.0.161
  path: /srv/nfs
  mountPath: /mnt/nfs
  size: 10Gi # 👈 must match manually defined PV
  request: 10Gi # 👈 must match PVC request
  storageClass: nfs-static
