image:
  repository: yasirabid96/dask-worker-rclone
  tag: latest
  pullPolicy: Always

scheduler:
  serviceType: NodePort

worker:
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 50
    cpu:
      targetAverageUtilization: 70

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  volumeMounts:
    - name: dask-nfs-volume
      mountPath: /mnt/nfs

  volumes:
    - name: dask-nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc # ✅ This must match exactly your bound PVC

nfs:
  server: 10.0.0.161 # ✅ NFS server IP
  path: /srv/nfs # ✅ Path shared by your NFS server
  mountPath: /mnt/nfs
  size: 10Gi # ✅ Should match `capacity` in the PV
  request: 10Gi # ✅ Should match PVC's requested storage
  storageClass: nfs-static # ✅ Matches the PV's StorageClass
