image:
  repository: yasirabid96/dask-worker-rclone
  tag: latest
  pullPolicy: Always

nfs:
  server: 203.101.229.227
  path: /srv/nfs
  mountPath: /mnt/nfs
  size: 10Gi
  request: 10Gi
  storageClass: nfs-static

scheduler:
  serviceType: NodePort

worker:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  volumeMounts:
    - name: dask-nfs-volume
      mountPath: /mnt/nfs

  volumes:
    - name: dask-nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
