image:
  repository: yasirabid96/dask-worker-rclone
  tag: latest
  pullPolicy: Always

scheduler:
  serviceType: NodePort

worker:
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 50
    cpu:
      targetAverageUtilization: 70

  # Correctly define resources for the container
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
