image:
  repository: yasirabid96/dask-worker-rclone
  tag: latest
  pullPolicy: Always

scheduler:
  serviceType: NodePort

worker:
  replicas: 2
  extraVolumes:
    - name: rclone-config
      secret:
        secretName: rclone-config
  extraVolumeMounts:
    - name: rclone-config
      mountPath: /root/.config/rclone
      readOnly: true
