apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dask-worker
  namespace: dask
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dask-worker
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
