apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-nfs-common
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: install-nfs-common
  template:
    metadata:
      labels:
        name: install-nfs-common
    spec:
      hostPID: true
      containers:
        - name: install-nfs-common
          image: ubuntu:20.04 # Use a specific version
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && \
              DEBIAN_FRONTEND=noninteractive apt-get install -y nfs-common && \
              echo "Installed nfs-common on $(hostname)" && \
              sleep infinity
          securityContext:
            privileged: true
          volumeMounts:
            - name: root-mount
              mountPath: /host
      volumes:
        - name: root-mount
          hostPath:
            path: /
      restartPolicy: Always
      tolerations:
        - operator: Exists
