apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-nfs-utils
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: install-nfs-utils
  template:
    metadata:
      labels:
        name: install-nfs-utils
    spec:
      hostPID: true
      containers:
        - name: install
          image: fedora:latest
          command:
            - /bin/bash
            - -c
            - |
              dnf install -y nfs-utils && sleep infinity
          securityContext:
            privileged: true
      tolerations:
        - operator: "Exists"
      restartPolicy: Always
