apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfs-installer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nfs-installer
  template:
    metadata:
      labels:
        app: nfs-installer
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: install-nfs
          image: fedora
          command:
            - /bin/bash
            - -c
            - |
              dnf install -y nfs-utils && sleep infinity
          securityContext:
            privileged: true
      tolerations:
        - operator: Exists
      restartPolicy: Always
