apiVersion: v1
kind: PersistentVolume
metadata:
  name: dask-nfs-pv
spec:
  capacity:
    storage: "{{ .Values.nfs.size }}"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dask-nfs
  nfs:
    path: "{{ .Values.nfs.path }}"
    server: "{{ .Values.nfs.server }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dask-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dask-nfs
  resources:
    requests:
      storage: "{{ .Values.nfs.request }}"
