apiVersion: v1
kind: PersistentVolume
metadata:
  name: dask-nfs-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dask-nfs
  mountOptions:
    - vers=4
  nfs:
    path: /srv/nfs
    server: 10.255.135.231

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dask-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dask-nfs
  resources:
    requests:
      storage: 1Gi
