apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dask-nfs-pvc
  namespace: dask
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
