apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-scheduler
  labels:
    app: dask
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      component: scheduler
  template:
    metadata:
      labels:
        app: dask
        component: scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          command: ["dask-scheduler"]
          ports:
            - containerPort: 8786
            - containerPort: 8787
