apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-static
provisioner: nfs.csi.k8s.io
parameters:
  server: 203.101.229.227
  share: /srv/nfs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
