apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-worker
  labels:
    app: dask
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dask
      component: worker
  template:
    metadata:
      labels:
        app: dask
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["dask-worker", "dask-scheduler:8786"]
          args: []
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /mnt/nfs
              name: dask-nfs-volume
      volumes:
        - name: dask-nfs-volume
          persistentVolumeClaim:
            claimName: dask-nfs-pvc
