apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-worker
  labels:
    app: dask
    component: worker
spec:
  replicas: { { .Values.worker.replicas | default 2 } }
  selector:
    matchLabels:
      app: dask
      component: worker
  template:
    metadata:
      labels:
        app: dask
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["dask-worker", "dask-scheduler:8786"]
          env:
            - name: RCLONE_CONFIG_PATH
              value: "{{ .Values.worker.configPath }}"
          args: []
