apiVersion: v1
kind: Service
metadata:
  name: dask-worker
  labels:
    app: dask
    component: worker
spec:
  clusterIP: None
  selector:
    app: dask
    component: worker
  ports:
    - name: worker
      port: 9000
      targetPort: 9000
