apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-worker
  labels:
    app: dask
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: dask
      component: worker
  template:
    metadata:
      labels:
        app: dask
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.name }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          volumeMounts:
            {{- range .Values.worker.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
      volumes:
        {{- range .Values.worker.extraVolumes }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secret.secretName }}
        {{- end }}
